Repository jshttp/cookie, pull requests merged in 2023-11, with the labels that each got.

#150 fix: typos in JSDoc
  index.js
Labels: pr

#149 fix: typos in History.md
  HISTORY.md
Labels: pr, docs

#140 Fixed typo in HISTORY.md: "pref" > "perf"
  HISTORY.md
Labels: pr, docs

#153 Add support for Partitioned.
  HISTORY.md
  README.md
  index.js
  test/serialize.js
Labels: enhancement, pr
